"""
Peak-to-peak co-accessibility via kNN-metacell correlation.

Ports ArchR's :func:`addCoAccessibility`. This is the peak-vs-peak cousin of
:func:`epione.tl.peak_to_gene` – same metacell framework, same correlation +
t-test + BH FDR, but the pair list is generated by a sliding window of
peak-peak distance rather than peak-gene distance.

Output is a DataFrame with one row per evaluated peak pair, columns:
    peak1, peak2, chrom, peak1_center, peak2_center, distance,
    correlation, t, p_value, fdr.

Also written to ``adata.uns[key_added]`` and ``adata.uns[key_added +
"_params"]`` unless ``inplace=False``.
"""
from __future__ import annotations

from typing import Optional, Tuple
import numpy as np
import pandas as pd
import scipy.sparse as sp
import scipy.stats as ss
from anndata import AnnData

from ..utils import console
from ._peak_to_gene import (
    _parse_peak_names,
    _build_metacell_indices,
    _aggregate,
    _zscore_columns,
    _bh_fdr,
)


def coaccessibility(
    adata: AnnData,
    *,
    use_rep: str = "X_iterative_lsi",
    n_metacells: int = 500,
    k_neighbors: int = 100,
    max_distance: int = 250_000,
    min_correlation: float = 0.0,
    alpha: float = 0.05,
    layer: Optional[str] = None,
    seed: int = 0,
    key_added: str = "coaccessibility",
    inplace: bool = True,
    verbose: bool = True,
) -> pd.DataFrame:
    """Peak-to-peak correlation across kNN-aggregated metacells.

    Parameters
    ----------
    adata
        Cells × peaks AnnData. ``adata.var_names`` must be interval-style
        (``chr:start-end``) and ``adata.obsm[use_rep]`` must hold an embedding
        (e.g. output of :func:`epione.tl.iterative_lsi`).
    use_rep, n_metacells, k_neighbors, seed
        Same semantics as :func:`epione.tl.peak_to_gene`.
    max_distance
        Maximum peak-centre ↔ peak-centre distance (bp). Peak pairs outside
        this window are never evaluated. Default 250 kb matches ArchR.
    min_correlation
        Drop pairs with ``|r| < min_correlation`` before returning (still
        reports how many were significant).
    alpha
        FDR threshold used only for the "significant" summary in the log.
    layer
        Use ``adata.layers[layer]`` instead of ``adata.X``.
    key_added
        Table is stored at ``adata.uns[key_added]`` (and the param dict at
        ``key_added + '_params'``).
    """
    if use_rep not in adata.obsm:
        raise KeyError(
            f"adata.obsm[{use_rep!r}] not found – run iterative_lsi first."
        )
    emb = np.asarray(adata.obsm[use_rep])

    X = adata.layers[layer] if layer is not None else adata.X
    if X.shape[0] != adata.n_obs:
        raise ValueError("peak matrix first dim must equal n_obs")

    # Peak coords
    peak_df = _parse_peak_names(adata.var_names)
    peak_df["center"] = ((peak_df["start"] + peak_df["end"]) // 2).astype(int)
    peak_df["peak_idx"] = np.arange(len(peak_df))
    if verbose:
        console.info(
            f"[coaccessibility] {len(peak_df):,} peaks | {adata.n_obs:,} cells"
        )

    # Metacells
    if verbose:
        console.info(
            f"[coaccessibility] Building {n_metacells} metacells x {k_neighbors} "
            f"neighbours from {use_rep}"
        )
    mc_idx = _build_metacell_indices(emb, n_metacells, k_neighbors, seed)
    n_mc = mc_idx.shape[0]

    if verbose:
        console.info("[coaccessibility] Aggregating peak matrix")
    peak_mc = _aggregate(X, mc_idx)                 # (n_mc, n_peaks)
    Pz = _zscore_columns(peak_mc)

    # Build pairs per chromosome (sliding window)
    if verbose:
        console.info(
            f"[coaccessibility] Finding peak pairs within ±{max_distance:,} bp"
        )
    pk_idx_1, pk_idx_2, dists = [], [], []
    for chrom, df in peak_df.groupby("chrom", sort=False):
        d = df.sort_values("center").reset_index(drop=True)
        centers = d["center"].to_numpy()
        idx = d["peak_idx"].to_numpy()
        n = len(centers)
        # For each i, find j in (i, n) with centers[j] - centers[i] <= max_distance
        j_start = np.arange(n)
        j_end = np.searchsorted(centers, centers + max_distance, side="right")
        for i in range(n):
            js = np.arange(i + 1, j_end[i])
            if js.size == 0:
                continue
            pk_idx_1.append(np.full(js.size, idx[i], dtype=np.int64))
            pk_idx_2.append(idx[js].astype(np.int64))
            dists.append((centers[js] - centers[i]).astype(np.int64))

    if not pk_idx_1:
        if verbose:
            console.warn("[coaccessibility] No peak pairs within max_distance.")
        df = pd.DataFrame(columns=[
            "peak1", "peak2", "chrom", "peak1_center", "peak2_center",
            "distance", "correlation", "t", "p_value", "fdr",
        ])
        if inplace:
            adata.uns[key_added] = df
        return df

    p1 = np.concatenate(pk_idx_1)
    p2 = np.concatenate(pk_idx_2)
    distance = np.concatenate(dists)
    if verbose:
        console.info(f"[coaccessibility] {len(p1):,} candidate peak pairs")

    # Chunked correlation: r = (Pz[:, p1] * Pz[:, p2]).sum(0) / (n_mc - 1)
    n_pairs = len(p1)
    max_chunk = max(1, int(256 * 2**20 / max(n_mc, 1) / 4))
    chunk_size = min(n_pairs, max(max_chunk, 100_000))
    r = np.empty(n_pairs, dtype=np.float32)
    for s in range(0, n_pairs, chunk_size):
        e = min(s + chunk_size, n_pairs)
        a = Pz[:, p1[s:e]]
        b = Pz[:, p2[s:e]]
        r[s:e] = ((a * b).sum(axis=0) / (n_mc - 1)).astype(np.float32)
    r = np.clip(r, -1.0, 1.0)

    df_deg = n_mc - 2
    r2 = np.clip(1 - r.astype(np.float64) ** 2, 1e-12, None)
    t = r * np.sqrt(df_deg / r2)
    p = 2.0 * ss.t.sf(np.abs(t), df_deg)
    fdr = _bh_fdr(p)

    peak_names = np.asarray(adata.var_names)
    out = pd.DataFrame({
        "peak1":         peak_names[p1],
        "peak2":         peak_names[p2],
        "chrom":         peak_df["chrom"].to_numpy()[p1],
        "peak1_center":  peak_df["center"].to_numpy()[p1],
        "peak2_center":  peak_df["center"].to_numpy()[p2],
        "distance":      distance,
        "correlation":   r,
        "t":             t.astype(np.float32),
        "p_value":       p.astype(np.float32),
        "fdr":           fdr.astype(np.float32),
    })

    if min_correlation > 0:
        out = out[out["correlation"].abs() >= min_correlation].reset_index(drop=True)

    if verbose:
        n_sig = int((out["fdr"] < alpha).sum())
        console.info(
            f"[coaccessibility] {len(out):,} pairs retained, "
            f"{n_sig:,} significant (FDR < {alpha})"
        )

    if inplace:
        adata.uns[key_added] = out
        adata.uns[key_added + "_params"] = {
            "use_rep": use_rep,
            "n_metacells": int(n_metacells),
            "k_neighbors": int(k_neighbors),
            "max_distance": int(max_distance),
            "min_correlation": float(min_correlation),
            "alpha": float(alpha),
            "seed": int(seed),
        }
    return out
